# Generated by Django 5.2.3 on 2025-06-23 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesturebattle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gesturetest',
            index=models.Index(fields=['user', '-tested_at'], name='gesturebatt_user_id_b1c481_idx'),
        ),
        migrations.AddIndex(
            model_name='gesturetest',
            index=models.Index(fields=['detected_gesture'], name='gesturebatt_detecte_fbfb54_idx'),
        ),
    ]
